name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build & Test
      run: ./gradlew installJest build

  publish:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Publication
      run: ./gradlew publishMavenPublicationToBuildRepository
    - uses: actions/checkout@master
      with:
        repository: juggernaut0/juggernaut0.github.io
        path: repo
        token: ${{ secrets.PUBLISH_TOKEN }}
    - name: Publish
      run: |
        cp -r build/repo/* repo/m2/repository
        cd repo
        git checkout -b kui-${{ github.sha }}
        git add m2
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update kui"
        git push origin kui-${{ github.sha }}
